### ISSUE TITLE
More functionality

### ISSUE THREAD

**Issue by jonomurphy** [Siggelicious/RetailFrames#1]
Hey there!

Great addon! Wanted to ask whether you'd consider adding more configuration options, such as the ability to have different profiles for different settings [BG/Arena/Raid], pets or no pets?

**Comment by DMV62** [comment]
I think the addon doesnt have support anymore.

**Comment by Pocokk** [comment]
@Siggelicious Apologize, do you plan to revisit and perhaps add/update the addon? Thank you.

**Comment by Siggelicious** [comment]
I stopped supporting this addon with the release of Classic TBC, unfortunately. I understand that more people are now drawn to private servers, as there aren't any official options for TBC currently, but I do not have enough time at hand to be supporting an addon like this.

Best of luck to you!

**Comment by jonomurphy** [comment]
No worries, and thanks for the response!

Do you know whether it would be possible by editing the LUA to hide/move the pet frames as well? If so, I'll get straight onto that.

Thanks again!

**Comment by Siggelicious** [comment]
I remember writing the pet frame as a self-contained module, so that should definitely be possible!
